### ISSUE TITLE
Allowing letter input on "9" mask

### ISSUE THREAD

**Issue by jourdanrodrigues** [candreoliveira/ngMask#133] opened 2017-03-08 18:21 UTC
**_ngMask: 3.1.1_**

My masks are:

- "9999-9999", for BR phone;
- "99.999-999", for zip code;
- "9 9999-9999", for BR mobile;
- "9999 9999 9999 9999", for credit card etc.

_I know is not relevant, it's just to say that I'm not using alien code_.

Is still possible to put characters on these fields.

**Comment by PhiLhoSoft** [comment] 2017-05-16 15:07
Looks like a duplicate of #113 where a solution is given.

**Comment by jourdanrodrigues** [comment] 2017-05-16 15:19
@PhiLhoSoft Thanks!

**Closed as completed** 2017-05-16 15:19 UTC
